// Generated by gencpp from file duckietown_msgs/PatrolBot.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_PATROLBOT_H
#define DUCKIETOWN_MSGS_MESSAGE_PATROLBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckietown_msgs
{
template <class ContainerAllocator>
struct PatrolBot_
{
  typedef PatrolBot_<ContainerAllocator> Type;

  PatrolBot_()
    : name()
    , direction()
    , id(0)  {
    }
  PatrolBot_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , direction(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;

   typedef int32_t _id_type;
  _id_type id;




  typedef boost::shared_ptr< ::duckietown_msgs::PatrolBot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::PatrolBot_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolBot_

typedef ::duckietown_msgs::PatrolBot_<std::allocator<void> > PatrolBot;

typedef boost::shared_ptr< ::duckietown_msgs::PatrolBot > PatrolBotPtr;
typedef boost::shared_ptr< ::duckietown_msgs::PatrolBot const> PatrolBotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::PatrolBot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/home/david/gazebo_test/catkin_ws/src/duckietown_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::PatrolBot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::PatrolBot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::PatrolBot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "515b9ef8adc1a831f89a147203c7da57";
  }

  static const char* value(const ::duckietown_msgs::PatrolBot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x515b9ef8adc1a831ULL;
  static const uint64_t static_value2 = 0xf89a147203c7da57ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/PatrolBot";
  }

  static const char* value(const ::duckietown_msgs::PatrolBot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string direction\n\
int32 id\n\
";
  }

  static const char* value(const ::duckietown_msgs::PatrolBot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.direction);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolBot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::PatrolBot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::PatrolBot_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_PATROLBOT_H
