// Generated by gencpp from file duckietown_msgs/RobotList.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_ROBOTLIST_H
#define DUCKIETOWN_MSGS_MESSAGE_ROBOTLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckietown_msgs
{
template <class ContainerAllocator>
struct RobotList_
{
  typedef RobotList_<ContainerAllocator> Type;

  RobotList_()
    : robot(0)  {
    }
  RobotList_(const ContainerAllocator& _alloc)
    : robot(0)  {
  (void)_alloc;
    }



   typedef int32_t _robot_type;
  _robot_type robot;




  typedef boost::shared_ptr< ::duckietown_msgs::RobotList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::RobotList_<ContainerAllocator> const> ConstPtr;

}; // struct RobotList_

typedef ::duckietown_msgs::RobotList_<std::allocator<void> > RobotList;

typedef boost::shared_ptr< ::duckietown_msgs::RobotList > RobotListPtr;
typedef boost::shared_ptr< ::duckietown_msgs::RobotList const> RobotListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::RobotList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::RobotList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/home/david/gazebo_test/catkin_ws/src/duckietown_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::RobotList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::RobotList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::RobotList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::RobotList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::RobotList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::RobotList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::RobotList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19238a8d0c7746376713b235eefb7a53";
  }

  static const char* value(const ::duckietown_msgs::RobotList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19238a8d0c774637ULL;
  static const uint64_t static_value2 = 0x6713b235eefb7a53ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::RobotList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/RobotList";
  }

  static const char* value(const ::duckietown_msgs::RobotList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::RobotList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 robot\n\
";
  }

  static const char* value(const ::duckietown_msgs::RobotList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::RobotList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::RobotList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::RobotList_<ContainerAllocator>& v)
  {
    s << indent << "robot: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_ROBOTLIST_H
