// Generated by gencpp from file duckietown_msgs/RobotName.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_ROBOTNAME_H
#define DUCKIETOWN_MSGS_MESSAGE_ROBOTNAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckietown_msgs
{
template <class ContainerAllocator>
struct RobotName_
{
  typedef RobotName_<ContainerAllocator> Type;

  RobotName_()
    : robot_name()
    , send(false)  {
    }
  RobotName_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)
    , send(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_name_type;
  _robot_name_type robot_name;

   typedef uint8_t _send_type;
  _send_type send;




  typedef boost::shared_ptr< ::duckietown_msgs::RobotName_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::RobotName_<ContainerAllocator> const> ConstPtr;

}; // struct RobotName_

typedef ::duckietown_msgs::RobotName_<std::allocator<void> > RobotName;

typedef boost::shared_ptr< ::duckietown_msgs::RobotName > RobotNamePtr;
typedef boost::shared_ptr< ::duckietown_msgs::RobotName const> RobotNameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::RobotName_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::RobotName_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/home/david/gazebo_test/catkin_ws/src/duckietown_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::RobotName_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::RobotName_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::RobotName_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::RobotName_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::RobotName_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::RobotName_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::RobotName_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78807f811fa3e05d59138ca9cc794ba9";
  }

  static const char* value(const ::duckietown_msgs::RobotName_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78807f811fa3e05dULL;
  static const uint64_t static_value2 = 0x59138ca9cc794ba9ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::RobotName_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/RobotName";
  }

  static const char* value(const ::duckietown_msgs::RobotName_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::RobotName_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_name\n\
bool send\n\
";
  }

  static const char* value(const ::duckietown_msgs::RobotName_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::RobotName_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
      stream.next(m.send);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotName_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::RobotName_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::RobotName_<ContainerAllocator>& v)
  {
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_name);
    s << indent << "send: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.send);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_ROBOTNAME_H
